### ISSUE TITLE
Universal configuration parser

### ISSUE THREAD

**Issue by denji** [AdUser/f2b#2]
Would you like to make a universal parser for configuration files?

Each [UCL](https://github.com/vstakhov/libucl) object can be serialized to one of the three supported formats:
- `JSON` - canonic json notation (with spaces indented structure);
- `Compacted JSON` - compact json notation (without spaces or newlines);
- `Configuration` - nginx like notation;
- `YAML` - yaml inlined notation.

**Comment by AdUser** [comment]
What you're trying to say?
