### ISSUE TITLE
help me

### ISSUE THREAD

**Issue by lflish** [AdUser/f2b#3]
I do ssh recent anti-blasting, but refer to your program, I do not compile the past, I edited it the wrong way, I came into f2b folder and cmake ./ this error. I have not used cmake.

**Comment by lflish** [comment]
Scanning dependencies of target f2b
[  1%] Building C object src/CMakeFiles/f2b.dir/daemon.c.o
cc1: error: unrecognized command line option "-Werror=format-security"
make[2]: **\* [src/CMakeFiles/f2b.dir/daemon.c.o] Error 1
make[1]: **\* [src/CMakeFiles/f2b.dir/all] Error 2
make: **\* [all] Error 2

**Comment by AdUser** [comment]
What system/compiler(version) are you using?

**Comment by lflish** [comment]
my system is redhat5,so cmake（version 2.6） is error,then i update cmake(2.8) version, cmake is success,but,makefile is error,because gcc is version 4.1?

**Comment by AdUser** [comment]
Yes, it's gcc error. Try cmake with this option:

cmake -DWITH_HARDENING=OFF .
make

**Comment by lflish** [comment]
thank you very much~
eg:
    if (cfg->study)
    {  
         #ifdef PCRE_CONFIG_JIT
             pcre_free_study(r->data);//undefind;it is my pcre is old?
         #else
             pcre_free(r->data);
         #endif
    }
pcre_free_study undefind,but i done success;
thanks.

**Comment by AdUser** [comment]
I'll make some #ifdef's a bit later this day.

**Comment by lflish** [comment]
Can you tell me how to use? I run /usr/local/sbin/f2b withdrew, directly after the ps - ef | grep f2b found no process.
/ usr/local/sbin/f2b
/ usr/local/bin/f2bc
/ usr/local/bin/f2b - source - the test
/ usr/local/bin/f2b - filter - test
/ usr/local/bin/f2b - backend - test

**Comment by AdUser** [comment]
You need to tune config first.

Go to `/usr/local/etc/f2b/conf-enabled` and make symlinks for needed config parts, like this:

```
05-source-files.conf -> ../conf-available/05-source-files.conf
10-backend-exec-ipset.conf -> ../conf-available/10-backend-exec-ipset.conf
15-filter-preg.conf -> ../conf-available/15-filter-preg.conf
```

Then create file 90-local.conf and add section like this:

``` ini
[jail:test]
enabled = yes
source = files:/path/to/logfile
filter = preg:/path/to/regexps/file
backend = exec-ipset:test
```

Then try to start f2b:

``` sh
f2b -t -c /usr/local/etc/f2b/f2b.conf # config test
f2b -d -c /usr/local/etc/f2b/f2b.conf # start in background
```

...and see in log for errors. By default, all logs goes to syslog with 'daemon' facility, so look in /var/log/daemon\* or /var/log/messages . This may be changed via `logdest` option in section [main]

**Comment by lflish** [comment]
in /usr/local/etc/f2b/conf-enabled file ,i have 3 file,
05-source-files.conf  
10-backend-exec-ipset.conf  //my firewall is iptables
15-filter-preg.conf

in file /usr/local/etc/f2b/f2b.conf
   1 [main]
  2 includes = /usr/local/etc/f2b/conf-enabled
  3 pidfile = /var/run/f2b.pid
  4 logdest = syslog
  5 loglevel = info
  6 logfile = /var/log/f2b.log
  7 user = root
  8 group = root
  9 daemon = yes
 10 
 11 [defaults]
 12 enabled  = yes
 13 bantime  = 3600
 14 findtime = 300
 15 expiretime = 14400
 16 incr_bantime = 0.0
 17 incr_findtime = 0.0
 18 maxretry = 5
 19 source   = files:/var/log/messages
 20 backend  = exec-ipset:banned
 21 
 22 [jail:ssh]
 23 enabled  = yes
 24 source  = files:/var/log/secure #my system is redhat,so ,login log is in the file
 25 filter  = preg:/usr/local/share/f2b/filters/ssh.preg
use the f2b.conf,i can SSH brute force crack ？

message:error
673 Oct 11 18:56:06 localhost f2b[13876]: jail 'ssh': source action 'start' failed -- 
674 Oct 11 18:56:06 localhost f2b[13876]: can't init jail 'ssh'
675 Oct 11 18:56:06 localhost f2b[13876]: no jails configured, exiting

**Comment by AdUser** [comment]
`jail 'ssh': source action 'start' failed` <- that's the source of problem

you need to install `iptables`, `ipset` tools and maybe fix paths in 10-backend-exec-ipset.conf
